version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
  - package-ecosystem: cargo
    directory: '/'
    open-pull-requests-limit: 100
    schedule:
      interval: 'daily'
    groups:
      cargo-toml:
        patterns:
          - "toml_edit"
          - "cargo-edit"
