name: 'something releaser installer'
description: 'install something-releaser'
author: 'anatawa12'
inputs:
  token:
    description: github token
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: './scripts/install.js'
