name: 'something releaser installer'
description: 'install something-releaser'
author: 'anatawa12'
inputs:
  token:
    description: github token
    required: true
    default: ${{ github.token }}
  target:
    description: the binary target to install
    required: false
  build-on-install:
    description: whether if build on install
    required: false
    default: 'false'
runs:
  using: 'node20'
  main: './scripts/install.js'
