[package]
name = "something-releaser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros", "fs", "io-util"] }
semver = "1.0.20"
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
uuid = { version = "1.6.1", features = ["v4"] }
home = "0.5.9"
pretty_env_logger = "0.5.0"
clap = { version = "4.4.12", features = ["derive"] }

[dev-dependencies]
httptest = "0.15.5"
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["process"] }
