$schema: "http://json-schema.org/draft-07/schema"
required:
  - git-user
  - version-changer
  - publish-environment
  - publish-command
additionalProperties: false
properties: 


  git-user:
    additionalProperties: false
    type: string
    description: the name of git user to be used. this will be configured at first


  version-changer:
    additionalProperties: false
    minProperties: 1
    properties:

      gradle-properties:
        additionalProperties: false
        description: change version via gradle.properties
        oneOf:
          - additionalProperties: false
            properties:
              property:
                type: string
                description: the name of a property has version name in properties file
                default: version
              path:
                type: string
                description: the path to gradle.properties
                default: 'gradle.properties'
          - items:
              additionalProperties: false
              properties:
                property:
                  type: string
                  description: the name of a property has version name in properties file
                  default: version
                path:
                  type: string
                  description: the path to gradle.properties


  publish-environment:
    additionalProperties: false
    minProperties: 1
    properties:

      gradle-maven:
        additionalProperties: false
        required:
          - repo
        properties: 
          repo: 
            oneOf:
              - $ref: '#/definitions/publish/gradle-maven-repo'
              - items:
                  $ref: '#/definitions/publish/gradle-maven-repo'
          sign:
            additionalProperties: false
            required:
              - gpg-key
              - gpg-pass
            properties: 
              gpg-key:
                type: string
              gpg-pass:
                type: string

      gradle-plugin-portal:
        additionalProperties: false
        description:
          Publish to gradle plugin portal via `com.gradle.plugin-publish` plugin.
          You need to apply `com.gradle.plugin-publish` plugin for project
          and configure pluginBundle.
        type: object
        required:
          - key
          - secret
        properties:
          key:
            type: string
          secret:
            type: string

      gradle-intellij:
        additionalProperties: false
        description:
          Publish to intellij plugin portal via `org.jetbrains.intellij` plugin.
          You need to apply `org.jetbrains.intellij` plugin for project 
          and configure publishPlugin.
        type: object
        required:
          - token
        properties:
          token:
            type: string

  publish-command:
    type: string

definitions:
  publish:
    gradle-maven-repo:
      additionalProperties: false
      description:
        Publish to maven repository via `maven-publish`.
        You need to apply `maven-publish` plugin for project
        and configure publications.
      required:
        - url
      properties:
        url:
          type: string
          description: The url to maven repository
        user:
          type: string
        pass:
          type: string
