name: CI
on: [push, pull_request]
jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust (rustup)
        run: rustup update stable --no-self-update && rustup default stable
      - run: cd command && cargo build
      - run: cd command && cargo test

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust (rustup)
        run: rustup update stable --no-self-update && rustup default stable
      - run: cargo fmt -- --check
