name: 'build-test'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run all
        env:
          GH_TOKEN: ${{ github.token }}
      # check if this action is valid
      - uses: ./

      # prepare bats for tests and run tests
      - run: npm install -g bats
      - run: bats shell-tests/*
        env:
          SOMETHING_RELEASER_SEMVER: 1
