name: 'build-test'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: ./scripts/build.js

      # check if this action is valid
      - uses: ./

      # prepare bats for tests and run tests
      - run: npm install -g bats
      - run: bats shell-tests/*
        env:
          SOMETHING_RELEASER_SEMVER: 1
